# Server Configuration
server.port=8080

# Application Info
spring.application.name=blue-green-demo

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
management.endpoint.health.show-details=always

# Logging
logging.level.root=INFO
logging.level.com.example.demo=DEBUG
